import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Water Tax' }).click();
  await page.getByRole('link', { name: 'New Plumber License' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('textbox', { name: ': First Name *' }).click();
  await page.getByRole('textbox', { name: ': First Name *' }).fill('Anand');
  await page.getByRole('textbox', { name: ': Middle Name' }).click();
  await page.getByRole('textbox', { name: ': Middle Name' }).fill('Ashok');
  await page.getByRole('textbox', { name: ': Middle Name' }).press('Tab');
  await page.getByRole('textbox', { name: ': Last Name * This field is' }).fill('Rane');
  await page.getByRole('textbox', { name: ': Mobile Number *' }).click();
  await page.getByRole('textbox', { name: ': Mobile Number *' }).fill('7989890680');
  await page.getByRole('textbox', { name: ': Address Line1 *' }).click();
  await page.getByRole('textbox', { name: ': Address Line1 *' }).fill('Mumbai');
  await page.getByText('Title Select Mr. Mrs. Miss. Dr. Prof. First Name Middle Name Last Name This').click();
  await page.getByRole('textbox', { name: ': Pin code *' }).click();
  await page.getByRole('textbox', { name: ': Pin code *' }).fill('211010');
  await page.getByRole('button', { name: ': Upload Photo *' }).click();
  await page.getByRole('button', { name: ': Upload Photo *' }).setInputFiles('Microsoft-Power-BI-.png');
  await page.getByRole('link', { name: 'Academic/Professional Details' }).click();
  await page.getByLabel('Qualification').selectOption('946');
  await page.getByRole('textbox', { name: 'Institute Name' }).click();
  await page.getByRole('textbox', { name: 'Institute Name' }).fill('Mumbai');
  await page.getByRole('textbox', { name: 'Institute Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Institute Address This field' }).fill('Mumbai');
  await page.getByRole('textbox', { name: 'Date of Passing' }).click();
  await page.getByRole('combobox').nth(3).selectOption('2017');
  await page.getByRole('link', { name: '1', exact: true }).click();
  await page.getByRole('textbox', { name: 'Percent/Grade' }).click();
  await page.getByRole('textbox', { name: 'Percent/Grade' }).fill('67');
  await page.getByRole('button', { name: 'Confirm to Proceed' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList1"]').click();
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList1"]').setInputFiles('ACK_COO.pdf');
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList2"]').click();
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList2"]').setInputFiles('COU.pdf');
  await page.getByRole('cell', { name: 'Choose File Upload' }).nth(3).click();
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList4"]').click();
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList4"]').setInputFiles('CTL.pdf');
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList5"]').click();
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList5"]').setInputFiles('DTL.pdf');
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList6"]').click();
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList6"]').setInputFiles('Duplicate license copy.pdf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Pass@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('DYEWT005');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' ACK_COO.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page1 = await page1Promise;
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' COU.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page2 = await page2Promise;
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' CTL.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page3 = await page3Promise;
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' DTL.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page4 = await page4Promise;
  const page5Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' Duplicate license copy.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page5 = await page5Promise;
  await page.getByRole('checkbox', { name: 'Marked All' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Scrutiny' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.locator('#lValue492').selectOption('Yes');
  await page.locator('#lValue496').click();
  await page.locator('#lValue496').fill('ok');
  await page.getByRole('textbox', { name: 'dd/mm/yyyy' }).click();
  await page.getByRole('link', { name: '26' }).click();
  await page.locator('#lValue498').click();
  await page.locator('#lValue498').fill('ok');
  await page.getByRole('button', { name: 'View / Edit' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByLabel('Collection Mode').selectOption('119');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  const page6Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Proceed' }).click();
  const page6 = await page6Promise;
  await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('EEWT004');
  await page.getByRole('textbox', { name: 'User ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByRole('checkbox', { name: 'Execute Plumber License' }).check();
  await page.locator('#executionDate').click();
  await page.getByRole('link', { name: '26' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Back' }).click();
});