import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://103.41.33.174:8069/CitizenHome.html');
  await page.getByRole('link', { name: 'English' }).click();
  await page.getByRole('link', { name: 'Citizen Login' }).click();
  await page.getByRole('textbox', { name: 'Login id' }).click();
  await page.getByRole('textbox', { name: 'Login id' }).fill('8208487562');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('textbox', { name: 'Enter Captcha Value' }).click();
  await page.getByRole('textbox', { name: 'Enter Captcha Value' }).fill('1044');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: ' Citizen Services' }).click();
  await page.getByRole('link', { name: 'Water Supply ' }).click();
  await page.getByRole('link', { name: 'Water Bill Payment' }).click();
  await page.locator('#connum').click();
  await page.locator('#connum').fill('A017198475');
  await page.getByRole('button', { name: ' Search' }).click();
  await page.goto('http://103.41.33.174:8069/WaterBillPayment.html?serachWaterBillPayment');
  await page.locator('#payAmount').click();
  await page.locator('#payAmount').fill('1302');
  await page.getByRole('radio', { name: 'Online' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.locator('#payeemail2').click();
  await page.locator('#cbBankid').selectOption('5');
  await page.getByRole('button', { name: 'Pay' }).click();
  await page.goto('https://pay1.getepay.in/getePaymentPages/api/payByVpa');
  await page.getByText('Mastercard, Visa, Rupay,').click();
  await page.getByRole('spinbutton', { name: 'Card Number Card Number' }).fill('41111111111111111');
  await page.locator('#form_ccform select[name="month"]').selectOption('06');
  await page.locator('#form_ccform select[name="year"]').selectOption('2026');
  await page.locator('#onamec').click();
  await page.locator('#onamec').fill('master card');
  await page.locator('#button_ccform').click();
  await page.locator('#button_ccform').click();
  await page.locator('#form_ccform').getByRole('textbox', { name: 'CVV' }).click();
  await page.locator('#form_ccform').getByRole('textbox', { name: 'CVV' }).fill('123');
  await page.locator('#button_ccform').click();
  await page.getByRole('textbox', { name: 'Enter OTP:' }).click();
  await page.getByRole('textbox', { name: 'Enter OTP:' }).fill('7926');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.goto('chrome-error://chromewebdata/');
  await page.getByRole('button', { name: 'Send anyway' }).click();
});