import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('CCOCFC053');
  await page.getByRole('textbox', { name: 'User ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Citizen Facilitation Centre' }).click();
  await page.getByRole('link', { name: 'Water Supply' }).click();
  await page.getByRole('link', { name: 'Change of Ownership' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.locator('#firstName').click();
  await page.locator('#firstName').fill('Sachin');
  await page.locator('#middleName').click();
  await page.locator('#middleName').fill('Ashok');
  await page.locator('#lastName').click();
  await page.locator('#lastName').fill('Joshi');
  await page.getByRole('textbox', { name: ': Mobile Number *' }).click();
  await page.getByRole('textbox', { name: ': Mobile Number *' }).fill('9879089080');
  await page.getByRole('textbox', { name: ': Address Line1 *' }).click();
  await page.getByRole('textbox', { name: ': Address Line1 *' }).fill('Mumbai');
  await page.getByRole('textbox', { name: ': Address Line1 *' }).press('Tab');
  await page.getByRole('textbox', { name: ': Address Line2' }).press('Tab');
  await page.getByRole('textbox', { name: ': Address Line3' }).press('Tab');
  await page.getByRole('textbox', { name: ': Pin code *' }).fill('211101');
  await page.getByLabel('Div').selectOption('300000001');
  await page.getByLabel('Ward').selectOption('500000003');
  await page.getByLabel('Ward').selectOption('500000004');
  await page.getByLabel('Zone').selectOption('600000014');
  await page.getByRole('textbox', { name: ': Connection No. *' }).click();
  await page.getByRole('textbox', { name: ': Connection No. *' }).fill('A010014738');
  await page.getByRole('button', { name: ' Search' }).click();
  await page.getByLabel('Transfer Mode').selectOption('144');
  await page.locator('[id="changeOwnerMaster.cooNoname"]').click();
  await page.locator('[id="changeOwnerMaster.cooNoname"]').fill('Chetan');
  await page.locator('[id="changeOwnerMaster.cooNolname"]').click();
  await page.locator('[id="changeOwnerMaster.cooNolname"]').fill('Joshi');
  await page.locator('#newOwner').click();
  await page.getByLabel('Gender').selectOption('80');
  await page.getByText('Confirm to Proceed Back').click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.locator('[id="changeOwnerMaster.fileList0"]').click();
  await page.locator('[id="changeOwnerMaster.fileList0"]').setInputFiles('Nagar Nigam Aligarh.pdf');
  await page.locator('[id="changeOwnerMaster.fileList1"]').click();
  await page.locator('[id="changeOwnerMaster.fileList1"]').setInputFiles('Kalyan Dombivli Municipal Corporation (UAT) (1).pdf');
  await page.locator('[id="changeOwnerMaster.fileList2"]').click();
  await page.locator('[id="changeOwnerMaster.fileList2"]').setInputFiles('Kalyan Dombivli Municipal Corporation (UAT).pdf');
  await page.locator('[id="changeOwnerMaster.fileList3"]').click();
  await page.locator('[id="changeOwnerMaster.fileList3"]').setInputFiles('DuplicateNonMeterBillPrintingReport.pdf');
  await page.getByRole('link', { name: 'Close' }).click();
  await page.locator('[id="changeOwnerMaster.fileList3"]').click();
  await page.locator('[id="changeOwnerMaster.fileList3"]').setInputFiles('WO_NWC.pdf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('form').filter({ hasText: 'कल्याण डोंबिवली महानगरपालिका (UAT) Application No. 2025054611 Applicant Name :' }).click();
  await page.locator('form').filter({ hasText: 'कल्याण डोंबिवली महानगरपालिका (UAT) Application No. 2025054611 Applicant Name :' }).click();
  await page.getByRole('button', { name: 'Print' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: '    DINESH BHALERAO' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('JEWT006');
  await page.getByRole('textbox', { name: 'User ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' Nagar Nigam Aligarh.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page1 = await page1Promise;
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' Kalyan Dombivli Municipal Corporation (UAT) (1).pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page2 = await page2Promise;
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' Kalyan Dombivli Municipal Corporation (UAT).pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page3 = await page3Promise;
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' WO_NWC.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page4 = await page4Promise;
  await page.getByRole('checkbox', { name: 'Marked All' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Scrutiny' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Portal Dept Login' }).click();
  await page.locator('#lValue467').selectOption('Yes');
  await page.getByRole('button', { name: 'View / Edit' }).click();
  await page.locator('#deptId').selectOption('5');
  await page.getByText('Field with * is mandatory ×').click();
  await page.getByLabel('Employee Name:').selectOption('314');
  await page.getByRole('textbox', { name: ': Date And Time: *' }).click();
  await page.getByRole('link', { name: '24' }).click();
  await page.getByText('PrevNextNovember 2025SuMoTuWeThFrSa').click();
  await page.getByRole('button', { name: 'Done' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('#lValue468').click();
  await page.getByRole('textbox', { name: 'dd/mm/yyyy' }).click();
  await page.getByRole('link', { name: '24' }).click();
  await page.locator('#frmScrutinyLabel').click();
  await page.getByLabel('Final Decision').selectOption('APPROVED');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.locator('[id="a"]').getByText('Pending Completed').click();
  await page.locator('[id="a"]').getByText('Pending Completed').click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(2).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('DYEWT007');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Scrutiny' }).click();
  await page.locator('#lValue471').selectOption('Yes');
  await page.locator('#lValue472').selectOption('Yes');
  await page.getByRole('row', { name: '1 If Final Decision is Yes' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.getByLabel('Collection Mode').selectOption('119');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  const page5Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Proceed' }).click();
  const page5 = await page5Promise;
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByRole('textbox', { name: 'वापरकर्ता आयडी' }).click();
  await page.getByRole('textbox', { name: 'वापरकर्ता आयडी' }).click();
  await page.getByRole('textbox', { name: 'वापरकर्ता आयडी' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('DYEWT007');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Pass@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.getByRole('button', { name: 'Approve' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Print' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
});