import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Citizen Facilitation Centre' }).click();
  await page.getByRole('link', { name: 'Water Supply' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('link', { name: 'No Dues Certificate' }).click();
  await page.getByRole('textbox', { name: ': First Name *' }).click();
  await page.getByRole('textbox', { name: ': First Name *' }).fill('Yogesh');
  await page.getByRole('textbox', { name: ': Last Name *' }).click();
  await page.getByRole('textbox', { name: ': Last Name *' }).fill('Patel');
  await page.getByRole('textbox', { name: ': Mobile Number *' }).click();
  await page.getByRole('textbox', { name: ': Mobile Number *' }).click();
  await page.getByRole('textbox', { name: ': Mobile Number *' }).fill('7890548783');
  await page.getByText('Title Select Mr. Mrs. Miss. Dr. Prof. First Name Middle Name Last Name Mobile').click();
  await page.getByRole('textbox', { name: ': Address Line1 *' }).click();
  await page.getByRole('textbox', { name: ': Address Line1 *' }).fill('Mumbai');
  await page.getByRole('textbox', { name: ': Pin code *' }).click();
  await page.getByRole('textbox', { name: ': Pin code *' }).fill('211001');
  await page.getByLabel('Div').selectOption('300000001');
  await page.getByLabel('Div').press('Tab');
  await page.getByLabel('Ward').press('ArrowDown');
  await page.getByLabel('Ward').selectOption('500000003');
  await page.getByLabel('Zone').selectOption('600000001');
  await page.getByRole('textbox', { name: ': Connection Number *' }).click();
  await page.getByRole('textbox', { name: ': Connection Number *' }).click();
  await page.getByRole('textbox', { name: ': Connection Number *' }).fill('A020003375');
  await page.getByRole('button', { name: ' View Dues' }).click();
  await page.getByText('Connection Number View Dues Reset Consumer Name Consumer Address Number of').click();
  await page.getByRole('textbox', { name: ': Number of Copies *' }).click();
  await page.getByRole('textbox', { name: ': Number of Copies *' }).fill('2');
  await page.getByRole('button', { name: 'Confirm to Proceed' }).click();
  await page.getByLabel('Collection Mode').selectOption('119');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Submit' }).click();
  const page1 = await page1Promise;
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
});