import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('JEWT002');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Water Tax' }).click();
  await page.getByRole('link', { name: 'Disconnection' }).click();
  await page.getByRole('textbox', { name: ': Connection No. *' }).click();
  await page.getByRole('textbox', { name: ': Connection No. *' }).fill('A010013096');
  await page.getByText('Connection No. Consumer Name Disconnection Type Select Permanent Disconnection').click();
  await page.getByText('Connection No. Consumer Name Disconnection Type Select Permanent Disconnection').click();
  await page.getByLabel('Disconnection Type').selectOption('427');
  await page.getByRole('textbox', { name: ': Disconnection Reason *' }).click();
  await page.getByRole('textbox', { name: ': Disconnection Reason *' }).fill('shift');
  await page.locator('#plumber').selectOption('100000033');
  await page.getByRole('button', { name: ' Search' }).click();
  await page.getByRole('textbox', { name: ': First Name *' }).click();
  await page.getByRole('textbox', { name: ': First Name *' }).fill('Ganes');
  await page.getByRole('textbox', { name: ': Last Name *' }).click();
  await page.getByRole('textbox', { name: ': First Name *' }).click();
  await page.getByRole('textbox', { name: ': First Name *' }).fill('Ganesh');
  await page.getByRole('textbox', { name: ': Last Name *' }).click();
  await page.getByRole('textbox', { name: ': Last Name *' }).fill('Mahale');
  await page.getByRole('textbox', { name: ': Mobile Number *' }).click();
  await page.getByRole('textbox', { name: ': Mobile Number *' }).fill('7890878787');
  await page.getByRole('textbox', { name: ': Address Line1 *' }).click();
  await page.getByRole('textbox', { name: ': Address Line1 *' }).fill('Mumbai');
  await page.getByText('Title Select Mr. Mrs. Miss. Dr. Prof. First Name Middle Name Last Name Mobile').click();
  await page.getByRole('textbox', { name: ': Pin code *' }).click();
  await page.getByRole('textbox', { name: ': Pin code *' }).fill('211010');
  await page.getByLabel('Div').selectOption('300000001');
  await page.getByLabel('Ward').selectOption('500000003');
  await page.getByRole('button', { name: 'Confirm to Proceed' }).click();
  await page.getByLabel('Zone').selectOption('600000001');
  await page.getByRole('button', { name: 'Confirm to Proceed' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.locator('[id="disconnectionEntity.fileList0"]').click();
  await page.locator('[id="disconnectionEntity.fileList0"]').setInputFiles('wo.pdf');
  await page.locator('[id="disconnectionEntity.fileList1"]').click();
  await page.locator('[id="disconnectionEntity.fileList1"]').setInputFiles('wo_COO.pdf');
  await page.locator('[id="disconnectionEntity.fileList2"]').click();
  await page.locator('[id="disconnectionEntity.fileList2"]').setInputFiles('Kalyan Dombivli Municipal Corporation (UAT) (1).pdf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.locator('#adminLoginForm').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' wo.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page1 = await page1Promise;
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' wo_COO.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page2 = await page2Promise;
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' Kalyan Dombivli Municipal' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page3 = await page3Promise;
  await page.getByRole('checkbox', { name: 'Marked All' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByRole('button', { name: 'Scrutiny' }).click();
  await page.locator('#lValue473').selectOption('Yes');
  await page.getByRole('row', { name: '1 Do you want to generate' }).getByRole('button').click();
  await page.locator('#deptId').selectOption('5');
  await page.getByLabel('Employee Name:').selectOption('312');
  await page.getByRole('textbox', { name: ': Date And Time: *' }).click();
  await page.getByRole('link', { name: '25', exact: true }).click();
  await page.getByRole('button', { name: 'Done' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('#lValue474').click();
  await page.getByRole('textbox', { name: 'dd/mm/yyyy' }).click();
  await page.getByRole('link', { name: '25', exact: true }).click();
  await page.locator('#lValue476').selectOption('Yes');
  await page.getByRole('row', { name: '4 Road Digging Details Yes' }).getByRole('button').click();
  await page.locator('#roadType0').selectOption('444');
  await page.locator('#roadLength0').click();
  await page.locator('#roadLength0').fill('6');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByLabel('Final Decision').selectOption('APPROVED');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(2).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('DYEWT004');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.locator('div').filter({ hasText: 'Employee not found in Kalyan' }).first().click();
  await page.locator('div').filter({ hasText: 'Employee not found in Kalyan' }).first().click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('DYEWT006');
  await page.locator('div').filter({ hasText: 'Employee not found in Kalyan' }).first().click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.locator('div').filter({ hasText: 'Employee not found in Kalyan' }).first().click();
  await page.locator('#selectedDistrict_chosen').getByRole('listitem').filter({ hasText: 'Kalyan Dombivli Municipal' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('DYEWT005');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.locator('div').filter({ hasText: 'Employee not found in Kalyan' }).first().click();
  await page.locator('#selectedDistrict_chosen').getByRole('listitem').filter({ hasText: 'Kalyan Dombivli Municipal' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Scrutiny' }).click();
  await page.locator('#lValue477').selectOption('Yes');
  await page.locator('#lValue478').selectOption('Yes');
  await page.getByRole('row', { name: '2 If Final Decision is Yes' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(2).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('CCOCFC053');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByLabel('Collection Mode').selectOption('119');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Proceed' }).click();
  const page4 = await page4Promise;
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('JEWT002');
  await page.getByRole('textbox', { name: 'User ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByRole('checkbox', { name: 'Execute Disconnection' }).check();
  await page.locator('#datepicker3').click();
  await page.getByRole('link', { name: '25', exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
});