import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Citizen Facilitation Centre' }).click();
  await page.getByRole('link', { name: 'Water Supply' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('link', { name: 'Renewal of Plumber License' }).click();
  await page.getByRole('textbox', { name: ': License Number' }).click();
  await page.getByRole('textbox', { name: ': License Number' }).fill('KDMC/WS/PLNO/52');
  await page.getByRole('button', { name: ' View Details' }).click();
  await page.getByRole('button', { name: 'Confirm to Proceed' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('× Please Upload Document :').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('ACK_COO.pdf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' ACK_COO.pdf' }).click();
  const page1 = await page1Promise;
  await page.getByRole('checkbox', { name: 'Marked All' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('DYEWT005');
  await page.getByRole('textbox', { name: 'User ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByTitle('Take an action').first().click();await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByRole('button', { name: 'Scrutiny' }).click();
  await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByRole('button', { name: 'Scrutiny' }).click();
  await page.locator('#lValue493').selectOption('Yes');
  await page.getByLabel('Final Decision').selectOption('APPROVED');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('EEWT004');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByRole('button', { name: 'Scrutiny' }).click();
  await page.locator('#lValue494').selectOption('Yes');
  await page.getByRole('button', { name: 'View / Edit' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('CCOCFC053');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('ba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByLabel('Collection Mode').selectOption('119');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Proceed' }).click();
  const page1 = await page1Promise;
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByRole('checkbox', { name: 'Execute Plumber License' }).check();
  await page.locator('#executionDate').click();
  await page.getByRole('link', { name: '26' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Print' }).click();
});