import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('CCOCFC053');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Citizen Facilitation Centre' }).click();
  await page.getByRole('link', { name: 'Water Supply' }).click();
  await page.getByRole('link', { name: 'Change of Usage' }).click();
  await page.getByRole('textbox', { name: ': Connection No. *' }).click();
  await page.getByRole('textbox', { name: ': Connection No. *' }).fill('1740000522');
  await page.getByRole('textbox', { name: ': Connection No. *' }).click();
  await page.getByRole('textbox', { name: ': Connection No. *' }).fill('A017200385');
  await page.getByRole('button', { name: ' Search' }).click();
  await page.locator('select[name="requestDTO.changeOfUsage.newTrmGroup1"]').selectOption('743');
  await page.locator('select[name="requestDTO.changeOfUsage.newTrmGroup2"]').selectOption('868');
  await page.locator('select[name="requestDTO.changeOfUsage.newTrmGroup3"]').selectOption('937');
  await page.locator('#newCsMeteredccn').selectOption('459');
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.locator('#remark').click();
  await page.locator('#remark').click();
  await page.locator('#remark').fill('usage change');
  await page.getByRole('button', { name: 'Confirm to Proceed' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.locator('input[name="requestDTO.fileList[0]"]').click();
  await page.locator('input[name="requestDTO.fileList[0]"]').setInputFiles('ACK_COO.pdf');
  await page.locator('input[name="requestDTO.fileList[1]"]').click();
  await page.locator('input[name="requestDTO.fileList[1]"]').setInputFiles('CTL.pdf');
  await page.locator('input[name="requestDTO.fileList[2]"]').click();
  await page.locator('input[name="requestDTO.fileList[2]"]').setInputFiles('DTL.pdf');
  await page.locator('input[name="requestDTO.fileList[3]"]').click();
  await page.locator('input[name="requestDTO.fileList[3]"]').setInputFiles('Duplicate license copy.pdf');
  await page.locator('input[name="requestDTO.fileList[5]"]').click();
  await page.locator('input[name="requestDTO.fileList[5]"]').setInputFiles('NTL_ack copy_not displayed properly.pdf');
  await page.getByRole('cell', { name: 'Choose File Upload', exact: true }).nth(1).click();
  await page.locator('input[name="requestDTO.fileList[6]"]').click();
  await page.locator('input[name="requestDTO.fileList[6]"]').setInputFiles('NTL_copy with regional data.pdf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.locator('a').filter({ hasText: 'Kalyan Dombivli Municipal' }).click();
  await page.locator('a').filter({ hasText: 'Kalyan Dombivli Municipal' }).click();
  await page.locator('div').filter({ hasText: 'Select Organisation Kalyan' }).first().click();
  await page.locator('div').filter({ hasText: 'Select Organisation Kalyan' }).nth(1).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' ACK_COO.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page1 = await page1Promise;
  await page.getByRole('cell', { name: ' CTL.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' CTL.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page2 = await page2Promise;
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' DTL.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page3 = await page3Promise;
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' Duplicate license copy.pdf' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page4 = await page4Promise;
  const page5Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' NTL_ack copy_not displayed' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page5 = await page5Promise;
  const page6Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: ' NTL_copy with regional data' }).click({
    modifiers: ['ControlOrMeta']
  });
  const page6 = await page6Promise;
  await page.getByRole('checkbox', { name: 'Marked All' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Scrutiny' }).click();
  await page.locator('#lValue461').selectOption('Yes');
  await page.getByRole('button', { name: 'View / Edit' }).click();
  await page.locator('#deptId').selectOption('5');
  await page.getByLabel('Employee Name:').selectOption('225');
  await page.getByRole('textbox', { name: ': Date And Time: *' }).click();
  await page.getByRole('link', { name: '26' }).click();
  await page.getByRole('button', { name: 'Done' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('tr:nth-child(2) > td:nth-child(3)').first().click();
  await page.getByRole('textbox', { name: 'dd/mm/yyyy' }).click();
  await page.getByRole('link', { name: '26' }).click();
  await page.getByLabel('Final Decision').selectOption('APPROVED');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(2).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('DYEWT004');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.locator('a').filter({ hasText: 'Kalyan Dombivli Municipal' }).click();
  await page.locator('div').filter({ hasText: 'Employee not found in Kalyan' }).first().click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('DYEWT005');
  await page.locator('a').filter({ hasText: 'Kalyan Dombivli Municipal' }).click();
  await page.locator('#selectedDistrict_chosen').getByRole('listitem').filter({ hasText: 'Kalyan Dombivli Municipal' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Scrutiny' }).click();
  await page.locator('#lValue465').selectOption('Yes');
  await page.locator('#lValue466').selectOption('Yes');
  await page.getByRole('row', { name: '1 If Final Decision is Yes' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Portal Dept Login' }).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('CCOCFC053');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByLabel('Collection Mode').selectOption('119');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  const page7Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Proceed' }).click();
  const page7 = await page7Promise;
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('DYEWT005');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByTitle('Take an action').first().click();
  await page.getByRole('checkbox', { name: 'Execute Change of Usage' }).check();
  await page.locator('#datepicker3').click();
  await page.getByRole('link', { name: '26' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('button', { name: 'Print' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Water Tax' }).click();
  await page.getByRole('link', { name: 'Meter Details Entry' }).click();
  await page.locator('[id="1"]').getByRole('link', { name: 'Edit Charge Master' }).click();
  await page.getByRole('textbox', { name: 'Meter Make' }).click();
  await page.getByRole('textbox', { name: 'Meter Make' }).fill('SRL');
  await page.getByRole('textbox', { name: 'Meter Number *' }).click();
  await page.getByRole('textbox', { name: 'Meter Number *' }).fill('789NP75436');
  await page.getByRole('textbox', { name: 'Initial Reading (IR) *' }).click();
  await page.getByRole('textbox', { name: 'Initial Reading (IR) *' }).fill('0');
  await page.getByRole('textbox', { name: 'Meter Max Reading *' }).click();
  await page.getByRole('textbox', { name: 'Meter Max Reading *' }).fill('99999');
  await page.getByText('× Application Details Service').click();
  await page.getByRole('textbox', { name: 'Meter Installation Date *' }).click();
  await page.getByRole('link', { name: '26' }).click();
  await page.getByRole('combobox').selectOption('462');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
});