import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://103.41.33.174:8069/CitizenHome.html');
  await page.getByRole('link', { name: 'English' }).click();
  await page.getByRole('link', { name: 'Citizen Login' }).click();
  await page.getByRole('textbox', { name: 'Login id' }).click();
  await page.getByRole('textbox', { name: 'Login id' }).fill('8208287562');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('textbox', { name: 'Enter Captcha Value' }).click();
  await page.getByRole('textbox', { name: 'Enter Captcha Value' }).fill('3989');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.goto('http://103.41.33.174:8069/CitizenHome.html');
  await page.getByRole('link', { name: 'Citizen Login' }).click();
  await page.getByRole('textbox', { name: 'Login id' }).click();
  await page.getByRole('textbox', { name: 'Login id' }).fill('8208487562');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('textbox', { name: 'Enter Captcha Value' }).click();
  await page.getByRole('textbox', { name: 'Enter Captcha Value' }).fill('2603');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: ' Citizen Services' }).click();
  await page.getByRole('link', { name: 'Water Supply ' }).click();
  await page.getByRole('link', { name: 'New water connection' }).click();
  await page.locator('#csFirstName').click();
  await page.locator('#csFirstName').fill('Dipesh Sane');
  await page.locator('#csFirstName').press('Tab');
  await page.locator('#csAddress1').click();
  await page.locator('#csAddress1').fill('Mumbai');
  await page.getByText('Consumer Name This field is required. Gender Select MALE FEMALE OTHERS Address').click();
  await page.locator('#csPinCode').click();
  await page.locator('#csPinCode').fill('420001');
  await page.locator('#csMobileNo').click();
  await page.locator('#csMobileNo').fill('7989897685');
  await page.getByLabel('Div').selectOption('300000001');
  await page.getByLabel('Ward').selectOption('500000003');
  await page.getByLabel('Zone').selectOption('600000001');
  await page.locator('#csCcncategory1').selectOption('745');
  await page.getByLabel('Sub-Category').selectOption('747');
  await page.locator('#propertyNo').click();
  await page.locator('#propertyNo').fill('B01021343500');
  await page.getByRole('button', { name: ' Search' }).click();
  await page.locator('#withoutBhagiRathi').selectOption('419');
  await page.getByLabel('Connection Type').selectOption('742');
  await page.locator('#trmGroup2').selectOption('789');
  await page.getByLabel('Premises Type').selectOption('929');
  await page.locator('#plumber').selectOption('100000091');
  await page.getByRole('checkbox', { name: 'Billing Address same as above' }).uncheck();
  await page.getByRole('checkbox', { name: 'Billing Address same as above' }).check();
  await page.getByRole('button', { name: 'Confirm to Proceed' }).click();
  await page.getByRole('row', { name: '1 Location Plan Mandatory' }).getByLabel('upload button').click();
  await page.getByRole('row', { name: '1 Location Plan Mandatory' }).getByLabel('upload button').setInputFiles('ACK_COO.pdf');
  await page.getByRole('row', { name: '2 Building Construction' }).getByLabel('upload button').click();
  await page.getByRole('row', { name: '2 Building Construction' }).getByLabel('upload button').setInputFiles('COU.pdf');
  await page.getByRole('row', { name: '3 Occupation Certificate' }).getByLabel('upload button').click();
  await page.getByRole('row', { name: '3 Occupation Certificate' }).getByLabel('upload button').setInputFiles('COU.pdf');
  await page.getByRole('link', { name: 'Close' }).click();
  await page.getByRole('row', { name: '3 Occupation Certificate' }).getByLabel('upload button').click();
  await page.getByRole('row', { name: '3 Occupation Certificate' }).getByLabel('upload button').setInputFiles('CTL.pdf');
  await page.getByRole('row', { name: '4 Property tax receipt' }).getByLabel('upload button').click();
  await page.getByRole('row', { name: '4 Property tax receipt' }).getByLabel('upload button').setInputFiles('DTL.pdf');
  await page.getByRole('row', { name: '6 NOC from the Owner' }).getByLabel('upload button').click();
  await page.getByRole('row', { name: '6 NOC from the Owner' }).getByLabel('upload button').setInputFiles('Duplicate license copy.pdf');
  await page.locator('#checkList6').click();
  await page.locator('#checkList6').setInputFiles('NTL_copy with regional data.pdf');
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('checkbox', { name: 'I have read and I accept the' }).check();
  await page.getByRole('checkbox', { name: 'I will submit hardcopy of the' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();