import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('CCOCFC053');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Pass@123');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Pass@123');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Citizen Facilitation Centre' }).click();
  await page.locator('[id="303"]').getByRole('link', { name: 'Track Complaint Status' }).click();
  await page.getByTitle('Home').click();
  await page.getByRole('link', { name: 'Citizen Facilitation Centre' }).click();
  await page.getByRole('link', { name: 'Water Supply' }).click();
  await page.getByRole('link', { name: 'Duplicate Bill' }).click();
  await page.getByRole('textbox', { name: ': First Name *' }).click();
  await page.getByRole('textbox', { name: ': First Name *' }).fill('Sahil');
  await page.getByRole('textbox', { name: ': Last Name *' }).click();
  await page.getByRole('textbox', { name: ': Last Name *' }).fill('Sharma');
  await page.getByRole('textbox', { name: ': Mobile Number *' }).click();
  await page.getByRole('textbox', { name: ': Mobile Number *' }).fill('7890564554');
  await page.getByRole('textbox', { name: ': Address Line1 *' }).click();
  await page.getByRole('textbox', { name: ': Address Line1 *' }).fill('Mumbai');
  await page.getByRole('textbox', { name: ': Pin code *' }).click();
  await page.getByRole('textbox', { name: ': Pin code *' }).fill('211011');
  await page.getByLabel('Div').selectOption('300000001');
  await page.getByLabel('Ward').selectOption('500000003');
  await page.getByLabel('Zone').selectOption('600000001');
  await page.getByRole('textbox', { name: ': Connection No. *' }).click();
  await page.getByRole('textbox', { name: ': Connection No. *' }).fill('A010004800');
  await page.getByText('Bill No').click();
  await page.locator('#bill').selectOption('508899');
  await page.locator('#noOfCopies').click();
  await page.locator('#noOfCopies').fill('2');
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByLabel('Collection Mode').selectOption('119');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Submit' }).click();
  const page1 = await page1Promise;
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Proceed' }).click();
  const page2 = await page2Promise;
  await page.getByRole('button', { name: 'Close' }).click();
});