import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://103.41.33.174/Skdcl/MainetService/Home.html');
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Citizen Facilitation Centre' }).click();
  await page.getByRole('link', { name: 'Water Bill Payment' }).click();
  await page.getByText('Connection Number Search').click();
  await page.getByRole('textbox', { name: ': Connection Number *' }).click();
  await page.getByRole('textbox', { name: ': Connection Number *' }).fill('A010002706');
  await page.getByRole('button', { name: ' Search' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.locator('#payAmount').click();
  await page.locator('#payAmount').fill('9133');
  await page.getByLabel('Collection Mode').selectOption('119');
  await page.getByRole('button', { name: 'Submit' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Proceed' }).click();
  const page1 = await page1Promise;
  await page1.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByRole('textbox', { name: 'वापरकर्ता आयडी' }).click();
  await page.getByRole('textbox', { name: 'वापरकर्ता आयडी' }).click();
  await page.getByTitle('English ').click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Pending' }).click();
  await page.getByRole('link', { name: 'Water Tax' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('link', { name: '  Logout' }).click();
  await page.getByTitle('English ').click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(2).click();
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('DYEWT005');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Water Tax' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.getByRole('link', { name: 'Receipt Reversal' }).click();
  await page.locator('div').filter({ hasText: 'Kalyan Dombivli Municipal' }).nth(4).click();
  await page.locator('a').filter({ hasText: 'Select' }).click();
  await page.locator('#depId_chosen').getByRole('textbox').fill('wat');
  await page.locator('#depId_chosen').getByRole('textbox').press('ArrowDown');
  await page.locator('#depId_chosen').getByRole('textbox').press('ArrowDown');
  await page.locator('#depId_chosen').getByRole('textbox').press('Enter');
  await page.getByRole('textbox', { name: ': Receipt/Bill No.*' }).click();
  await page.getByRole('textbox', { name: ': Receipt/Bill No.*' }).fill('31851');
  await page.locator('.accordion-toggle').click();
  await page.getByRole('textbox', { name: 'DD/MM/YYYY' }).click();
  await page.getByRole('link', { name: '28' }).click();
  await page.getByRole('button', { name: ' Search' }).click();
  await page.getByRole('button', { name: 'Reverse' }).click();
  await page.getByRole('textbox', { name: ': Reason *' }).click();
  await page.getByRole('textbox', { name: ': Reason *' }).fill('delete receipt');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('Nagar Nigam Aligarh.pdf');
  await page.getByRole('button', { name: ' Delete' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
});