import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://103.41.33.174/Skdcl/CitizenHome.html');
  await page.getByRole('link', { name: 'English' }).click();
  await page.getByRole('link', { name: 'Citizen Login' }).click();
  await page.getByRole('textbox', { name: 'Login id' }).click();
  await page.getByRole('textbox', { name: 'Login id' }).fill('8208487562');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Mba@1234');
  await page.getByRole('textbox', { name: 'Enter Captcha Value' }).click();
  await page.getByRole('textbox', { name: 'Enter Captcha Value' }).fill('2460');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: ' Citizen Services' }).click();
  await page.getByRole('link', { name: 'Water Supply ' }).click();
  await page.getByRole('link', { name: 'Water Supply ' }).click();
  await page.getByRole('link', { name: 'Water Supply ' }).click();
  await page.getByRole('link', { name: 'Plumber License', exact: true }).click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.getByRole('textbox', { name: ': Address Line1 *' }).click();
  await page.getByRole('textbox', { name: ': Address Line1 *' }).fill('Mumbai');
  await page.getByLabel('Div').selectOption('300000001');
  await page.getByLabel('Ward').selectOption('500000003');
  await page.getByLabel('Zone').selectOption('600000001');
  await page.getByRole('button', { name: 'upload button' }).click();
  await page.getByRole('button', { name: 'upload button' }).setInputFiles('14.10.2025_18.56.54_REC.png');
  await page.getByRole('link', { name: 'Academic/Professional Details' }).click();
  await page.getByLabel('Qualification').selectOption('945');
  await page.getByRole('cell').nth(2).click();
  await page.getByRole('textbox', { name: 'Institute Name' }).click();
  await page.getByRole('textbox', { name: 'Institute Name' }).fill('Mumbai');
  await page.getByRole('textbox', { name: 'Institute Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Institute Address This field' }).fill('Mumbai');
  await page.getByRole('textbox', { name: 'Institute Address This field' }).press('Tab');
  await page.getByRole('textbox', { name: 'Date of Passing This field is' }).click();
  await page.getByRole('combobox').nth(2).selectOption('2019');
  await page.getByRole('link', { name: '3', exact: true }).click();
  await page.getByRole('textbox', { name: 'Percent/Grade' }).click();
  await page.getByRole('textbox', { name: 'Percent/Grade' }).fill('61');
  await page.getByRole('button', { name: 'Confirm to Proceed' }).click();
  await page.getByRole('row', { name: '1 10th Marksheet / Passing' }).getByLabel('upload button').click();
  await page.getByRole('row', { name: '1 10th Marksheet / Passing' }).getByLabel('upload button').setInputFiles('ACK_COO.pdf');
  await page.getByRole('row', { name: '2 Diploma/Degree Marksheet' }).getByLabel('upload button').click();
  await page.getByRole('row', { name: '2 Diploma/Degree Marksheet' }).getByLabel('upload button').setInputFiles('COU.pdf');
  await page.getByRole('row', { name: '4 Experience certificate' }).getByLabel('upload button').click();
  await page.getByRole('row', { name: '4 Experience certificate' }).getByLabel('upload button').setInputFiles('CTL.pdf');
  await page.getByRole('row', { name: '5 Residance Proof of KDMC' }).getByLabel('upload button').click();
  await page.getByRole('row', { name: '5 Residance Proof of KDMC' }).getByLabel('upload button').setInputFiles('DTL.pdf');
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList6"]').click();
  await page.locator('[id="plumberLicenseReqDTO.fileCheckList6"]').setInputFiles('Duplicate license copy.pdf');
  await page.getByRole('checkbox', { name: 'I will submit hardcopy of the' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
});